//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_item
    {
        public long id { get; set; }
        public long productId { get; set; }
        public long cartId { get; set; }
        public string sku { get; set; }
        public double price { get; set; }
        public double discount { get; set; }
        public short quantity { get; set; }
        public short active { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string content { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
    }
}
