//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSCDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long id { get; set; }
        public long userId { get; set; }
        public long orderId { get; set; }
        public string code { get; set; }
        public short type { get; set; }
        public short mode { get; set; }
        public short status { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public string content { get; set; }
    
        public virtual order order { get; set; }
        public virtual USER USER { get; set; }
    }
}
